// <auto-generated />
using ManageStudent1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ManageStudent1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210211085149_AlterStudentsData")]
    partial class AlterStudentsData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ManageStudent1.Models.Student", b =>
                {
                    b.Property<string>("CIN")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Filiere")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CIN");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            CIN = "ha123",
                            Adresse = "Youssoufia",
                            Filiere = 0,
                            IsActive = true,
                            Nom = "benn",
                            Prenom = "sana"
                        },
                        new
                        {
                            CIN = "ha456",
                            Adresse = "Safi",
                            Filiere = 1,
                            IsActive = false,
                            Nom = "salman",
                            Prenom = "samir"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
